[package]
name = "qv"
version = "0.1.0"
authors = ["maxgurewitz <maxthegeek1@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.*"
serde = "1.0.*"
serde_derive = "1.0.*"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
