[package]
name = "qv"
version = "0.1.0"
authors = ["maxgurewitz <maxthegeek1@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-rc"
serde = "1.0.*"
serde_derive = "1.0.*"
diesel = { version = "1.4.*", features = ["postgres", "r2d2"] }
dotenv = "0.9.*"
r2d2 = "0.8.*"
