version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - 5432 
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash wait-for.sh -t 60 db:5432 -- cargo-watch -w ./src -w Cargo.toml -x run
    environment: 
      - DATABASE_URL=postgres://postgres:@db/qv
    depends_on: 
      - db
    links:
      - db
    ports:
      - 8000:8000 
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry

  integration_test:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash wait-for.sh -t 120 server:8000 -- cargo-watch -w ./tests -x 'test integration'
    environment: 
      - BASE_URL=http://server:8000/api
      - RUST_BACKTRACE=1
    depends_on: 
      - server
    links:
      - server
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local