version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - 5432 
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: cargo-watch -x run
    volumes:
      - ./server:/usr/src/app
    environment: 
      - DATABASE_URL=postgres://postgres:@db/qv
    depends_on: 
      - db
    links:
      - db
    ports:
      - 8000:8000 
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local